apiRules:
- include:
    uidRegex: ^nickmaltbie\.TemplateUnityProject
    type: Namespace
- include:
    uidRegex: ^nickmaltbie\.TemplateUnityProject\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace